name: Integration Test (Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  validate-action:
    name: Validate Docker Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a test command inside the container
        uses: ./
        with:
          rust_version: '1.88.0'
          cargo_lambda_version: '1.8.5'
          command: |
            cargo lambda -V && \
            cd examples/test-compilation/ &&
            cargo lambda build --release --output-format zip >> out.log 2> err.log &&
            [ -f err.log ] && echo "# Failed with error \n <pre>$(cat err.log)</pre>" >> "$GITHUB_STEP_SUMMARY" || echo -n "# Compiled sucessfully \n<summary>Output: <details><pre>$(cat out.log)</pre></details><summary>" >> "$GITHUB_STEP_SUMMARY"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-target-zip
          path: |
            examples/test-compilation/target/lambda/test-compilation/
