name: Integration Test (Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  validate-action:
    name: Validate Docker Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a test command inside the container
        uses: ./
        with:
          rust_version: '1.88.0'
          cargo_lambda_version: '1.8.5'
          command: |
            cargo lambda -V && \
            cd examples/test-compilation/ &&
            cargo lambda build --release --output-format zip > out.log 2> error.log &&
            [ -e "$PWD/error.log" ] && [ ! -s "$PWD/error.log" ] && [ -f "$PWD/out.log" ] && echo -n "# Compiled sucessfully \n<summary>Output: <details><pre>$(cat out.log)</pre></details><summary>" >> "$GITHUB_STEP_SUMMARY" || [ -f "$PWD/error.log" ] && echo "# Failed with error \n <pre>$(cat error.log)</pre>" >> "$GITHUB_STEP_SUMMARY"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: ${{ env.GITHUB_ACTIONS_RUNNER != 'act' }}
        with:
          name: lambda-target-zip
          path: |
            examples/test-compilation/target/lambda/test-compilation/
      - name: Echo output on ACT
        if: ${{ env.GITHUB_ACTIONS_RUNNER == 'act' }}
        run: echo "$GITHUB_STEP_SUMMARY"
