# .github/workflows/continuous-integration.yml

name: Continuous Integration

# This workflow runs on pushes to the main branch and on any pull request.
on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    name: Build and Test Action
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the action
        run: npm run build

      - name: Run tests
        run: npm test
