name: Integration Test (Docker)

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  validate-action:
    name: Validate Docker Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a test command inside the container
        uses: ./
        with:
          command: 'cargo-lambda --version'
          rust-version: '1.78.0'
          cargo-lambda-version: '1.2.0'
