name: Draft a new Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number to release (e.g., v1.2.3)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  draft-release:
    name: Draft Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create Draft Release
        run: >
          gh release create "${{ github.event.inputs.version }}"
          --title "${{ github.event.inputs.version }}"
          --notes "Automated draft release. Please update the changelog notes here."
          --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
